BHoM/GSA_Toolkit

GSA_Engine/Convert/ToBHoM.cs
GSA_Engine/Convert/ToGsa.cs
GSA_Engine/GSA_Engine.csproj
GSA_Test/Program.cs

https://github.com/BHoM/BHoM/pull/395
https://github.com/BHoM/BHoM_Engine/pull/776
Closes #81
Aligning with changes to the Node class in the BHoM
Any of the sample files as well as any of the previously working scripts.
- All methods affected by `Node` class property change made in https://github.com/BHoM/BHoM/pull/395 updated. No change made to any of the method interfaces

Aligning with changes to the Node class

---

GSA_Test/GSA_Test.csproj
GSA_Test/Program.cs

https://github.com/BHoM/BHoM/pull/509
Closes #102 
Renaming Queries to Request. Only change in testproject, non in the production code

Query to Request in test project

---

GSA_Engine/Convert/ToBHoM.cs

Closes #104 
- TryGetValue for material extraction when pulling sections to avoid crashing
- Undefined material as steel for now until a more permanent solution is in place, including warning message raised.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/GSA_Toolkit/GSA_Toolkit-Issue104-UndefinedMaterial?csf=1&e=J76RSh

Gsa toolkit issue104 pull undefined material as steel

---

.github/ISSUE_TEMPLATE/api_changed.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/compliance.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/test_script.md

Fixes #106 
N/A
- Added IssueTemplates

GSA_Toolkit: Issue templates

---

GSA_Adapter/Properties/AssemblyInfo.cs
GSA_Adapter_Legacy/Properties/AssemblyInfo.cs
GSA_Engine/Properties/AssemblyInfo.cs
GSA_Mongo/Properties/AssemblyInfo.cs
GSA_Test/Properties/AssemblyInfo.cs
GSA_oM/Properties/AssemblyInfo.cs

Closes #108 
Updates the `AssemblyFileVersion` to `2.3.0.0`

GSA_Toolkit: Update Assembly File Version

---

GSA_Adapter/GSA_Adapter.csproj
GSA_Adapter/Properties/AssemblyInfo.cs
GSA_Engine/GSA_Engine.csproj
GSA_Engine/Properties/AssemblyInfo.cs
GSA_oM/Properties/AssemblyInfo.cs

Closes #113 
Copy locals to false for all BHoM assembly references
Assembly version updated to 2.4

Update assembly file version to 2.4 and copy locals to false

---

GSA_Adapter/CRUD/Create.cs
GSA_Adapter/GSAAdapter.cs

Closes #117 
- Add optional boolean for if errors should be rasied from COMcall method, defaulting to true
- Setting said boolean to false for generating CAT sections
https://burohappold.sharepoint.com/:f:/s/BHoM/EuY51LbYbL5ClkOuFjX7g6oBdhjCP_-ZlA4pEv3GQ3FD_w?e=erz2yv

No error messages for trying to create CAT sections

---

GSA_Adapter/Properties/AssemblyInfo.cs
GSA_Engine/Properties/AssemblyInfo.cs
GSA_oM/Properties/AssemblyInfo.cs

Closes #119
Make sure that:
- All the .csproj files in the solution have the properties  `AssemblyFileVersion` to `3.0.0.0` and `AssemblyVersion` to `3.0.0.0`.
- The AssemblyCopyright reads `[assembly: AssemblyCopyright("Copyright © https://github.com/BHoM")]`
- Update `AssemblyFileVersion` to `3.0.0.0`
- Update `AssemblyVersion` to `3.0.0.0`

Update AssemblyVersion and AssemblyFileVersion to 3.0.0.0

---

GSA_Adapter/CRUD/Create.cs
GSA_Adapter/CRUD/UpdateObjects.cs
GSA_Adapter/CRUD/UpdateProperty.cs
GSA_Adapter/GSAAdapter.cs

https://github.com/BHoM/BHoM_Adapter/pull/151
Closes #121 
Updating adapter to align with changes in the parent BHoMAdapter
All previous scripts should still be working as before.
Fort macro tests, please see:
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FGSA%5FToolkit%2F%5FMacro%2FPush

Aligning with changes in BHoMAdapter

---

GSA_Adapter/Properties/AssemblyInfo.cs
GSA_Engine/Properties/AssemblyInfo.cs
GSA_oM/Properties/AssemblyInfo.cs

Closes #133 
Update assembly file version to 3.1

Update assembly file version to 3.1

---

GSA_Adapter/Convert/ToGsa/Loads/LoadCombination.cs
GSA_Engine/GSA_Engine.csproj
GSA_Engine/Modify/SetAnalysisType.cs
GSA_oM/Enum/TaskType.cs
GSA_oM/Fragments/AnalysisTaskFragment.cs
GSA_oM/GSA_oM.csproj

Closes #148 
Add fragment to control stage and analysis type for loadcombinations in GSA
https://burohappold.sharepoint.com/:f:/s/BHoM/EnTSE6K_GsVDsVo2WNu4GZUBCBEWRSSXoL3ayYbaC9iItA?e=sidATA

Expose analysis type and stage for combinations

---

GSA_Adapter/GSA_Adapter.csproj
GSA_Engine/GSA_Engine.csproj

https://github.com/BHoM/BHoM/pull/704
https://github.com/BHoM/BHoM_Engine/pull/1484
https://github.com/BHoM/BHoM_Adapter/pull/193
Closes #146 
Adds references to Dimensional_oM where necessary and 'using' statments where that is necessary 
to comply with the changes in https://github.com/BHoM/BHoM/pull/704

Update IElement references with the Dimensional_oM

---

GSA_oM/Fragments/AnalysisTaskFragment.cs

https://github.com/BHoM/BHoM/pull/711
https://github.com/BHoM/BHoM_Engine/pull/1495
Fixes #152

Renaming IBHoMFragment -> IFragment

---

GSA_Adapter/CRUD/ReadResults.cs

Closes #154 
Adding missing actionconfig to dispatch call.
https://burohappold.sharepoint.com/:f:/s/BHoM/EjNbKzufwltMkE3SqVnNg20B048TowRQVO1UyB-RUHcPng?e=SZZXvI
Check that the BarForces can be pulled both with a FilterRequest specifying the type, as well as with the ResultRequests.

Fix pulling results by type with filter request

---

GSA_Adapter/CRUD/ReadResultsElements.cs

Closes #156 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/GSA_Toolkit/GSA_Toolkit-%23156-BarForceReadingErrorWithDummyElements?csf=1&e=CsUoAQ

Changing method for extracting all Bar element ids to check for dummy tag

---

GSA_oM/Enum/ConcreteDesignSpecification.cs
GSA_oM/Enum/Country.cs
GSA_oM/Enum/SteelDesignSpecification.cs
GSA_oM/GSA_oM.csproj

Closes #151
@johannaisak this should have 0 functional change. COuld you check that things are still working as before.
@FraserGreenroyd adding you as CI checker 😉

GSA_Toolkit: Fix compliance

---

GSA_Adapter/GSA_Adapter.csproj
GSA_Engine/GSA_Engine.csproj
GSA_oM/GSA_oM.csproj

Closes #171 
Copy local to false for all BHoM references. Also fixed release build folder (as flagged by compliance) and making sure non of the references has a version on them.
Should not have any functional change. But good to run a simple test.
- Fix release build folder

Copy local to false for all BHoM references

---

README.md

Closes #175
Point to correct build core in readme

Point to correct build core in readme

---

GSA_Adapter/Convert/ToGsa/Loads/LoadCombination.cs
GSA_Adapter/GSAAdapter.cs
GSA_Engine/Create/GSAConfig.cs
GSA_Engine/GSA_Engine.csproj
GSA_Engine/Modify/SetAnalysisType.cs
GSA_Engine/Versioning_32.json
GSA_oM/Enum/AnalysisType.cs
GSA_oM/Enum/ConcreteDesignSpecification.cs
GSA_oM/Enum/Country.cs
GSA_oM/Enum/SteelDesignSpecification.cs
GSA_oM/Fragments/AnalysisTaskFragment.cs
GSA_oM/GSA_oM.csproj
GSA_oM/Settings/GSAConfig.cs
GSA_oM/Versioning_32.json

Closes #178
Update namespace of oM and Engine
https://burohappold.sharepoint.com/:f:/s/BHoM/EnM9pRCIaNFElgPdT_4we-sBI4GL4fhRszxUIIp_0BzvMA?e=tIiNNX

Update namespace of oM and Engine

---

GSA_Adapter/GSA_Adapter.csproj
GSA_Engine/GSA_Engine.csproj
GSA_oM/GSA_oM.csproj

https://github.com/BHoM/admin/issues/5
Closes #

Updated references and post build

---

GSA_Adapter/CRUD/ReadResults.cs
GSA_Adapter/CRUD/ReadResultsElements.cs
GSA_Adapter/CRUD/ReadResultsGlobal.cs
GSA_Adapter/GSA_Adapter.csproj
GSA_Engine/GSA_Engine.csproj

https://github.com/BHoM/BHoM/pull/911
Aligning with migration of Results from Common_oM to Analytical_oM.
Also, removing reference to Common_oM as no longer needed.

Aligning with changes migrating Results to Analytical_oM

---

GSA_Adapter/CRUD/ReadResults.cs
GSA_Adapter/CRUD/ReadResultsElements.cs
GSA_Adapter/Convert/FromGsa/Results/Results.cs

https://github.com/BHoM/BHoM/pull/912
- Align with changes in Structure_oM making results immutable
- Change objectIds to integers
- Attempt to extract mode
https://burohappold.sharepoint.com/:f:/s/BHoM/EjNbKzufwltMkE3SqVnNg20B048TowRQVO1UyB-RUHcPng?e=TcDp0m

Align with changes in Structure_oM making results immutable

---

GSA_Adapter/CRUD/Update.cs

Closes #183
Makes sure Update method works as it should for FEMeshes
Create - read - update for buildings:
https://burohappold.sharepoint.com/:f:/s/BHoM/EgLyzStwfWpGi7sSnAxSKNYBIyRhMp90JNyRQ_ozaUD-9g?e=YdKLS2

Fix update for FEMeshes

---

GSA_Adapter/CRUD/Read.cs
GSA_Adapter/CRUD/ReadResults.cs

https://github.com/BHoM/BHoM_Adapter/pull/244
Closes #187 
Removing support for pulling results with filter request, instead raising error stating what request that should be used.
Testing that error messages show up:
https://burohappold.sharepoint.com/:f:/s/BHoM/EpJzc3cX8wxFlD34ESjLjX4BepFblb73yqAEWHe8l1GuDA?e=iuLZct
For testing general results functionality:
https://burohappold.sharepoint.com/:f:/s/BHoM/EqqZu_1Sr0lIkfBdRPg8TBQBBsLM3bh3YedOFyiiI5-_tA?e=Ri0dJ9

Remove support for pulling results with filter request, adding error messaging

---

GSA_Adapter/CRUD/Create.cs
GSA_Adapter/Convert/FromGsa/Elements/RigidLink.cs
GSA_Adapter/Convert/ToGsa/Elements/RigidLink.cs

/BHoM/BHoM/pull/961
Closes #
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Structure_oM/Issue921-RigidLink%20property%20rename/Test%20Rigid%20Links%20-%20multi%20adapter.gh?csf=1&web=1&e=iDXtGs

Renamed RigidLink master/slave to primary/secondary

---

GSA_Adapter/Convert/ToGsa/Group.cs
GSA_Adapter/Convert/ToGsa/Loads/AreaLoads.cs
GSA_Adapter/Convert/ToGsa/Loads/BarLoads.cs
GSA_Adapter/Convert/ToGsa/Loads/NodeLoad.cs
GSA_Adapter/GSAAdapter.cs

https://github.com/BHoM/BHoM/pull/969
Link to main issue:
https://github.com/BHoM/BHoM/issues/946
Aligning with updates turning `Load<T>` into `IElementLoad<T>`
https://burohappold.sharepoint.com/:f:/s/BHoM/Em_LdUZqgX1KuIVqdNMiGJcBlPpuLhdHOREUu3lv_eSfTQ?e=72gT4a

Align with changes of Load<T> to IELementLoad<T>

---

GSA_Adapter/Convert/ToGsa/Loads/BarLoads.cs
GSA_Adapter/Convert/ToGsa/Loads/ForceType.cs

Closes #191 
Fixes the distribution of loads to match the BHoM definition. Raising errors for cases that can not be easily resolved.
Also fixing type, updating from tri-linear to patch
Issue test:
https://burohappold.sharepoint.com/:f:/s/BHoM/EiqHlJ1iFfhCm7I6iY6COdYBzOfQiV1gLmxbbW26_lwcSA?e=prY4df
General load tests:
https://burohappold.sharepoint.com/:f:/s/BHoM/EjE55YVx2IVCg3BjvBozJokB_1pz0ajFCnjmr8PN6m2few?e=wVX232

Fix BarVaryingLoad distributions

---

GSA_Adapter/Convert/FromGsa/Properties/SectionProperty.cs

Closes #199
Material pulling for explicit sections got lost here:
https://github.com/BHoM/GSA_Toolkit/pull/141
Simply adding it back in.

Materials read for Explicit sections

---

GSA_Adapter/Convert/FromGsa/Properties/SectionProperty.cs
GSA_Adapter/Convert/ToGsa/Properties/SectionProperty.cs
GSA_Adapter/GSA_Adapter.csproj

https://github.com/BHoM/BHoM/pull/1030
https://github.com/BHoM/BHoM_Engine/pull/2063
Related to https://github.com/BHoM/BHoM/issues/756
- Aligning with migration of shape profiles from Geometry to Spatial

Aligning with changes to ShapeProfiles

---

GSA_Adapter/CRUD/Read.cs
GSA_Adapter/Convert/FromGsa/Elements/Node.cs
GSA_Adapter/Convert/ToGsa/Elements/Bar.cs
GSA_Adapter/Convert/ToGsa/Loads/LoadCombination.cs
GSA_oM/Fragments/DummyTag.cs
GSA_oM/GSA_oM.csproj

Closes #204 
Remove use of custom data by:
- Removing fallback on custom data for task type for loadcombinations
- Cleaning up unused code
- Changing DummyTagging to use a new DummyTag fragment instead of CustomData

Remove custom data

---

GSA_Adapter/Convert/ToGsa/Loads/BarLoads.cs
GSA_Adapter/Convert/ToGsa/Loads/ForceType.cs

https://github.com/BHoM/BHoM/pull/1074
https://github.com/BHoM/BHoM_Engine/pull/2138
- Align with changes from `BarTemperatureLoad` and `AreaTemperatureLoad` to `BarUniformTemperatureLoad` and `AreaUniformTemperatureLoad`

Align with changes to BarUniformTemperatureLoad and AreaUniformTemperatureLoad

---

GSA_Adapter/Convert/ToGsa/Loads/BarLoads.cs

https://github.com/BHoM/BHoM_Engine/pull/2146/
https://github.com/BHoM/BHoM_Engine/issues/2135
Aligning with methods being removed from Structure_Engine.
This is only adding an additional using, so can safely be merged before others.

Aligning with changes in Structure_Engine

---

GSA_Adapter/AdapterActions/Execute.cs

Closes #221 
Making sure the SaveAs functionality works as intended:
- Checking the the directory exists, if not, creates the directory
- Checking that the path name is valid
Simply run the script an check that a model has been created in the test folder:
https://burohappold.sharepoint.com/:f:/s/BHoM/ErX0Y0BFbGNAhyTSV5iOxvMBxadA7tzS6mciIT13a_Ou3A?e=oDjve5

Fixing issues with SaveAs

---

GSA_Adapter/GSAAdapter.cs

Closes #226
[Test File #226](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&web=1&e=EyCiGC&cid=7cceaccf%2D019d%2D4813%2Da7a1%2Dd5a3a1d5c525&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FGSA%5FToolkit%2F%23226%2DPush%20Loadcase%20with%20Load%2F%23226%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FGSA%5FToolkit%2F%23226%2DPush%20Loadcase%20with%20Load)
This PR adds a dependency on Loadcase for ILoad and IElementLoad in the GSA Adapter. Loadcases will automatically be pushed to GSA when pushing Loads.

Add dependency on Loadcase for ILoad and IElementLoad

---

GSA_Adapter/CRUD/Create.cs
GSA_Adapter/CRUD/Read.cs
GSA_Adapter/Convert/FromGsa/Elements/Node.cs
GSA_Adapter/Convert/ToGsa/Elements/Node.cs

Closes #167 
Adding support for pushing and pulling local coordinates for nodes
https://burohappold.sharepoint.com/:f:/s/BHoM/EmmagkWc9BlIuit1igtMdW0BpRQb84Xd0pBEQamF_v-h2A?e=5F2IaQ

Adding support for pushing local axis for nodes

---

GSA_Adapter/Convert/ToGsa/Properties/SurfaceProperties.cs

[#1197](https://github.com/BHoM/BHoM/pull/1197)
Closes #223
[Test File](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FGSA%5FToolkit%2F%23223%20%2D%20Add%20ability%20to%20set%20Load%20Panel%20Support%20Pattern%20to%20Auto%2F%23223%20%2D%20Add%20ability%20to%20set%20Load%20Panel%20Support%20Pattern%20to%20Auto%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FGSA%5FToolkit%2F%23223%20%2D%20Add%20ability%20to%20set%20Load%20Panel%20Support%20Pattern%20to%20Auto)
Adding support to set 2D property support pattern to Auto in GSA.

Add ability to set Load Panel Support Pattern to Auto

---

GSA_Adapter/CRUD/Create.cs
GSA_Adapter/Convert/FromGsa/Elements/FEMesh.cs
GSA_Adapter/Convert/FromGsa/Elements/Spacer.cs
GSA_Adapter/Convert/FromGsa/Properties/Material.cs
GSA_Adapter/Convert/ToGsa/Elements/FEMesh.cs
GSA_Adapter/Convert/ToGsa/Elements/Spacer.cs
GSA_Adapter/Convert/ToGsa/Properties/FormFindingProperties.cs
GSA_Adapter/Convert/ToGsa/Properties/Material.cs
GSA_Adapter/Convert/ToGsa/Properties/SpacerProperty.cs
GSA_Adapter/Convert/ToGsa/Properties/SurfaceProperties.cs
GSA_Adapter/Convert/ToGsa/_ToGsa.cs
GSA_Adapter/GSAAdapter.cs
GSA_Adapter/GSA_Adapter.csproj
GSA_oM/Elements/Spacer.cs
GSA_oM/Enum/SpacerLengthType.cs
GSA_oM/Enum/SpacerType.cs
GSA_oM/FormFindingProperties/SoapStress1D.cs
GSA_oM/FormFindingProperties/SoapStress2D.cs
GSA_oM/GSA_oM.csproj
GSA_oM/MaterialFragments/Fabric.cs
GSA_oM/SpacerProperties/SpacerProperty.cs
GSA_oM/SurfaceProperties/FabricPanelProperty.cs

Adds fabric material, fabric panel property, spacers, spacer properties, soap stress plus enables pushing of these
Closes #232 
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/GSA_Toolkit/%23232%20-%20AddSupportForPushingFabricStructures/fabric%20push.gh?csf=1&web=1&e=rBhXn8
Adds fabric material, fabric panel property, spacers, spacer properties, soap stress + enables push of these

Add support for pushing fabric structures

---

GSA_Adapter/Convert/FromGsa/Properties/SectionProperty.cs
GSA_Adapter/Convert/ToGsa/Properties/Material.cs
GSA_Engine/Modify/SetAnalysisType.cs

Closes #246 
See BHoM/admin#9
Just compliance, should mean no functional change.

Remove calls to GetShallowClone

---

GSA_Adapter/AdapterActions/Execute.cs

https://github.com/BHoM/BHoM_Adapter/pull/303
Closes #248
Adding support for the Exit command
https://burohappold.sharepoint.com/:f:/s/BHoM/EjpTgU6jo_tJr30rbJs0a_gBnZnhI1rYcv3aQ-Yc3A6E2g?e=fenJ0J

Add implementation of Exit command

---

GSA_Adapter/Convert/FromGsa/Loads/Loadcase.cs
GSA_Adapter/Convert/ToGsa/Elements/Node.cs

Done is support of, but compiles without https://github.com/BHoM/BHoM_Engine/pull/2738
Align with removed methods from Structure_Engine

Align with changes in Structure_Engine

---

GSA_Adapter/Properties/AssemblyInfo.cs
GSA_Engine/Properties/AssemblyInfo.cs
GSA_oM/Properties/AssemblyInfo.cs

Update Assembly Information to include description

Update Assembly Information

---

GSA_Engine/GSA_Engine.csproj

Closes #266 
Fix compliance issue identified in https://github.com/BHoM/GSA_Toolkit/pull/244/checks?check_run_id=8595866469

Fix project compliance relating to Adapter_oM

---

GSA_Adapter/Convert/FromGsa/Properties/SectionProperty.cs

https://github.com/BHoM/BHoM_Datasets/pull/122
Aligns hardcoded paths to datasets migrated to discipline superfolder.

Align with migration of Structures datasets to subfolder

---

GSA_Adapter/CRUD/Read.cs
GSA_Adapter/Convert/FromGsa/Properties/FormFindingProperties.cs
GSA_Adapter/GSA_Adapter.csproj
GSA_Engine/GSA_Engine.csproj
GSA_oM/GSA_oM.csproj

Added new functionality to pull form finding properties (Soap Stress 1D and Soap Stress 2D).
Closes #294 
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&web=1&e=qBkOOh&cid=ac585af7%2Deee7%2D427f%2Dad7d%2D58e55a61714b&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FGSA%5FToolkit%2F%23294%2DPull%20form%20finding%20properties&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b

Pull Form Finding Properties

---

altConfigs.txt

Fix altConfigs

---

GSA_Adapter/Convert/FromGsa/Elements/Bar.cs
GSA_Adapter/Convert/FromGsa/Elements/Spacer.cs
GSA_Adapter/Convert/ToGsa/Elements/Bar.cs
GSA_Adapter/Convert/ToGsa/Elements/Spacer.cs
GSA_oM/Elements/Spacer.cs
GSA_oM/Versioning_71.json

https://github.com/BHoM/BHoM/pull/1579

Align with rename StartNode/EndNode to Start/End

---

GSA_Adapter/Properties/AssemblyInfo.cs
GSA_Engine/Properties/AssemblyInfo.cs
GSA_oM/Properties/AssemblyInfo.cs

Update AssemblyFileVersion to 7.3
Remove previous version attributes

Update AssemblyFileVersion to 7.3

---

GSA_Adapter/CRUD/ReadResultsElements.cs

Closes #322 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/GSA_Toolkit/%23340-BarDisplacement-unit-issue?csf=1&web=1&e=WQkQ8M
- Updated `BarDisplacement` unit factor.

Change BarDisplacement unit factor

---

GSA_Adapter/CRUD/Create.cs
GSA_Adapter/Convert/ToGsa/Elements/Joint.cs
GSA_oM/Elements/Joint.cs

Closes #341 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/GSA_Toolkit/%23342-Add-support-for-creating-and-pushing-Joints-to-GSA?csf=1&web=1&e=uPZoSf

Add support for creating and pushing Joints to GSA
